### ISSUE TITLE
Invalid public key input

### ISSUE THREAD

**Issue by houyunlu** [SoilLabs/Solana-Foam#1]
```js
          throw new Error(`Invalid public key input`);
```
It seems it from this line: 
https://github.com/SoilLabs/Solana-Foam/blob/c94e8a8cf9c2d266e4812416ccfbf9fdb8ef9709/index.mjs#L33-L33

          
, the `Fdt.metadata.address` is empty

**Comment by TDCBQ** [comment]
I have also encountered this problem. Can you provide a more detailed template

**Comment by xiaomaogy** [comment]
Yes really confused here. I tried to put in the public address for my solana address in the ftd.json's metadata->address field, but it gave me the error like: invalid transaction: Transaction failed to sanitize accounts offsets correctly

**Comment by frankkeepgoing** [comment]
same issue.
