### ISSUE TITLE
throw new Error('failed to get info about account ' + publicKey.toBase58() + ': ' + e)

### ISSUE THREAD

**Issue by CoderLeno** [SoilLabs/Solana-Foam#2]
(node:39761) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39761) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
your address:  xxx
/xxx/Solana-Foam-main/node_modules/@solana/web3.js/lib/index.cjs.js:7780
      throw new Error('failed to get info about account ' + publicKey.toBase58() + ': ' + e);
            ^

Error: failed to get info about account 76DjQGd9pxfdwxBVWhH1mpdhV6VFFsBP2amfs81RytvW: TypeError: fetch failed
    at Connection.getAccountInfo (/xxx/Solana-Foam-main/node_modules/@solana/web3.js/lib/index.cjs.js:7780:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AccountClient.getAccountInfo (/xxx/Solana-Foam-main/node_modules/@coral-xyz/anchor/dist/cjs/program/namespace/account.js:277:16)
    at async file:///xxx/Solana-Foam-main/index.mjs:43:19

**Comment by frankkeepgoing** [comment]
![image](https://github.com/SoilLabs/Solana-Foam/assets/17020313/3137418d-5a6d-4f90-a14c-daf22629f9f8)
same issue. somebody can help ? seems accout not found.

**Comment by tomiezhang** [comment]
+1
