### ISSUE TITLE
I cant withdraw sol

### ISSUE THREAD

**Issue by lesikone** [SoilLabs/Solana-Foam#3]
I cant withdraw about 10 sol for almost 24 hours.

I couldnt mint as well, these are the logs i see on my failed tx:

2 Unknown program instruction
> Program log: Instruction: Mintftd
> Invoking System Program
  > Program returned success
> Invoking System Program
  > Program returned success
> Program log: panicked at 'index out of bounds: the len is 10 but the index is 10', programs/ftd/src/lib.rs:419:13
> Program BFEtYvLqoWfj15xwapzoN62xHedP4AS718v36RCj9vKe  consumed 41448 of 1400000 compute units
> Program returned error: SBF program panicked

I still cant claim my sol. What can i do?

My address: AEdkH26yDgFibnPLs4eQgV4DYBFesZpYq35zHD2Cx82j

**Comment by SoilLabs** [comment]
Don't worry, I'm solving your problem

**Comment by SoilLabs** [comment]
> I cant withdraw about 10 sol for almost 24 hours.
> 
> I couldnt mint as well, these are the logs i see on my failed tx:
> 
> 2 Unknown program instruction
> 
> > Program log: Instruction: Mintftd
> > Invoking System Program
> > Program returned success
> > Invoking System Program
> > Program returned success
> > Program log: panicked at 'index out of bounds: the len is 10 but the index is 10', programs/ftd/src/lib.rs:419:13
> > Program BFEtYvLqoWfj15xwapzoN62xHedP4AS718v36RCj9vKe  consumed 41448 of 1400000 compute units
> > Program returned error: SBF program panicked
> 
> I still cant claim my sol. What can i do?
> 
> My address: AEdkH26yDgFibnPLs4eQgV4DYBFesZpYq35zHD2Cx82j

Don't worry, I'm solving your problem

**Comment by lesikone** [comment]
Let me know when fixied, please!

**Comment by SoilLabs** [comment]
> Let me know when fixied, please!

try again

**Comment by lesikone** [comment]
![image](https://github.com/SoilLabs/Solana-Foam/assets/67560280/48e4ffa5-1832-40d2-a8d1-71efa6eadcb6)
I still cant claim, but i see this on my screen ^

I cant see these logs on dev console in chrome:

0
: 
"Program BFEtYvLqoWfj15xwapzoN62xHedP4AS718v36RCj9vKe invoke [1]"
1
: 
"Program log: Instruction: Claim"
2
: 
"Program log: epoch_id:477215,epoch_total_join_times:2,dividend_times:1,dividend_amount:3288151,refund_amount:95000000"
3
: 
"Program data: kKzRVpBXVHMfSAcAAAAAAFcsMgAAAAAAwJWpBQAAAAABAAAAAAAAAA=="
4
: 
"Program BFEtYvLqoWfj15xwapzoN62xHedP4AS718v36RCj9vKe consumed 25446 of 200000 compute units"
5
: 
"Program BFEtYvLqoWfj15xwapzoN62xHedP4AS718v36RCj9vKe success"

But when i click claim i get error message :
Failed! Transaction not confirmed, try again.

**Comment by lesikone** [comment]
![image](https://github.com/SoilLabs/Solana-Foam/assets/67560280/496e0688-c4cb-4e7b-92a0-dd1656d89079)
This happen when i click "claim"

**Comment by SoilLabs** [comment]
> ![image](https://private-user-images.githubusercontent.com/67560280/293454517-496e0688-c4cb-4e7b-92a0-dd1656d89079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDg2MTgsIm5iZiI6MTcwMzk0ODMxOCwicGF0aCI6Ii82NzU2MDI4MC8yOTM0NTQ1MTctNDk2ZTA2ODgtYzRjYi00ZTdiLTkyYTAtZGQxNjU2ZDg5MDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE0NTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZGQ3YjAyYTg0ZTViMzQwYTkyMzA1ZGMzZjM5ZDFiNzIyNzQxZWJmYThhYTI0ZDM4ZWVjODcyMTkwNTM5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7MJlVXni32N3FyPwKyk4H5qjEYorW6D_WhCTMwvzUM8) This happen when i click "claim"

You used script but commented harvest function？

**Comment by lesikone** [comment]
I didnt comment anything! For now, i am just clicking "claim" button and check for logs in chrome dev console to share this logs with you!

**Comment by SoilLabs** [comment]
> I didnt comment anything! For now, i am just clicking "claim" button and check for logs in chrome dev console to share this logs with you!

refresh page try again.

**Comment by lesikone** [comment]
![image](https://github.com/SoilLabs/Solana-Foam/assets/67560280/6a010a1a-1b0a-46db-9340-12c8a51d307e)
As for now phantom confirmation window pops up, but it says only +0.09829 sol. But from the screenshot above i need to claim
10.9318 sol (unclaimed refund + unclaimed bonus)

**Comment by SoilLabs** [comment]
> ![image](https://private-user-images.githubusercontent.com/67560280/293490188-6a010a1a-1b0a-46db-9340-12c8a51d307e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTkzNzUsIm5iZiI6MTcwMzk5OTA3NSwicGF0aCI6Ii82NzU2MDI4MC8yOTM0OTAxODgtNmEwMTBhMWEtMWIwYS00NmRiLTkzNDAtMTJjOGE1MWQzMDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA1MDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYjZlZTg0YTYzNWZlZGVjYjdmMWYzNDIxMzdiM2M0NDFhZWQ4NzkzMjE2NzU2ZTY0M2QxOTRjZGVkMzcwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7m7b525vl5FhjX_cTybie0Hi2d4KU58JBhf0cELMAQk) As for now phantom confirmation window pops up, but it says only +0.09829 sol. But from the screenshot above i need to claim 10.9318 sol (unclaimed refund + unclaimed bonus)
> 
> Should i accept the transaction? I think it should say +10.9318 ?

accept about ten times

**Comment by lesikone** [comment]
It worked! I have finally claimed all my sol! Thank you so so much!
